"""Convert tracked EZKL proof.json into a Solidity fixture for Foundry CI.

The generated Solidity file is intentionally ephemeral. It lets Foundry deploy
and exercise the canonical generated Halo2 verifier against the exact tracked
proof without hand-copying thousands of proof bytes into version control.

Supported tracked proof representation:
- ``proof``: JSON array of byte values (0..255), or ``hex_proof``;
- ``instances[0]``: exactly 138 little-endian 32-byte hex field elements.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

EXPECTED_SIGNALS = 138


def _proof_bytes(value: dict[str, Any]) -> bytes:
    if isinstance(value.get("hex_proof"), str):
        text = value["hex_proof"]
        if not text.startswith("0x"):
            raise ValueError("hex_proof must be 0x-prefixed")
        return bytes.fromhex(text[2:])

    raw = value.get("proof")
    if not isinstance(raw, list) or not raw:
        raise ValueError("proof.json must contain non-empty proof[] or hex_proof")
    out = bytearray()
    for index, item in enumerate(raw):
        if not isinstance(item, int) or not 0 <= item <= 255:
            raise ValueError(f"proof[{index}] must be an integer byte")
        out.append(item)
    return bytes(out)


def _signals(value: dict[str, Any]) -> list[int]:
    instances = value.get("instances")
    if (
        not isinstance(instances, list)
        or len(instances) != 1
        or not isinstance(instances[0], list)
    ):
        raise ValueError("proof.json must contain exactly one instances[] vector")
    encoded = instances[0]
    if len(encoded) != EXPECTED_SIGNALS:
        raise ValueError(
            f"expected {EXPECTED_SIGNALS} public signals, got {len(encoded)}"
        )

    signals: list[int] = []
    for index, item in enumerate(encoded):
        if not isinstance(item, str):
            raise ValueError(f"instances[0][{index}] must be a hex string")
        try:
            raw = bytes.fromhex(item)
        except ValueError as exc:
            raise ValueError(f"instances[0][{index}] is invalid hex") from exc
        if len(raw) != 32:
            raise ValueError(
                f"instances[0][{index}] must encode exactly 32 bytes, got {len(raw)}"
            )
        signals.append(int.from_bytes(raw, byteorder="little"))
    return signals


def render_fixture(proof: bytes, signals: list[int]) -> str:
    assignments = "\n".join(
        f"        values[{index}] = {value};" for index, value in enumerate(signals)
    )
    return f'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @notice GENERATED by zkml/src/ezkl/export_foundry_fixture.py.
/// Do not commit as a canonical artifact; regenerate from tracked proof.json.
library ZkmlV2ProofFixture {{
    function proof() internal pure returns (bytes memory) {{
        return hex"{proof.hex()}";
    }}

    function signals() internal pure returns (uint256[] memory values) {{
        values = new uint256[]({EXPECTED_SIGNALS});
{assignments}
    }}
}}
'''


def generate(proof_path: Path, output_path: Path) -> dict[str, int]:
    try:
        value = json.loads(proof_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid proof JSON: {exc}") from exc
    if not isinstance(value, dict):
        raise ValueError("proof JSON root must be an object")

    proof = _proof_bytes(value)
    signals = _signals(value)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(render_fixture(proof, signals), encoding="utf-8")
    return {"proof_bytes": len(proof), "public_signals": len(signals)}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--proof",
        type=Path,
        default=Path("zkml/ezkl/proof.json"),
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("contracts/test/generated/ZkmlV2ProofFixture.sol"),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    result = generate(args.proof, args.output)
    print(json.dumps({**result, "output": str(args.output)}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
