#!/bin/bash
# run_training_ablation.sh — Edge-type training ablation study
# Generated by exp_l10_training_ablation.py
#
# IMPORTANT: The --ablate-edge-type flag is NOT yet implemented in train.py.
# Before running, add this to TrainConfig and trainer.py (see exp_l10 docstring).
#
# Run one at a time (each takes ~1-2 days on RTX 3070 8GB).
# Monitor with: tail -f ml/logs/<logfile>
#
set -e
LOG_SUFFIX=$(date +%Y%m%d)
echo "Starting ablation study. LOG_SUFFIX=${LOG_SUFFIX}"

# --- baseline (no ablation) ---
# Estimated F1 impact: N/A — reference run
TRANSFORMERS_OFFLINE=1 TRITON_CACHE_DIR=/tmp/triton_cache PYTHONPATH=. \
  nohup ml/.venv/bin/python ml/scripts/train.py \
  --gnn-layers 8 --gnn-prefix-k 48 --gnn-prefix-warmup-epochs 15 \
  --epochs 60 --batch-size 8 --gradient-accumulation-steps 8 \
  --loss-fn asl --compile --use-amp --phase2-edge-types 6 8 9 \
  --jk-entropy-reg-lambda 0.005 \
  --experiment-name sentinel-ablation-v1 \
  --run-name ablation-baseline \
  \
  >> ml/logs/ablation-baseline-${LOG_SUFFIX}.log 2>&1 &

echo "Launched: ablation-baseline"
sleep 5  # brief pause between launches

# --- ablate edge type 0 (UNKNOWN) ---
# Estimated F1 impact: Neutral — no structural role
TRANSFORMERS_OFFLINE=1 TRITON_CACHE_DIR=/tmp/triton_cache PYTHONPATH=. \
  nohup ml/.venv/bin/python ml/scripts/train.py \
  --gnn-layers 8 --gnn-prefix-k 48 --gnn-prefix-warmup-epochs 15 \
  --epochs 60 --batch-size 8 --gradient-accumulation-steps 8 \
  --loss-fn asl --compile --use-amp --phase2-edge-types 6 8 9 \
  --jk-entropy-reg-lambda 0.005 \
  --experiment-name sentinel-ablation-v1 \
  --run-name ablation-et0-unknown \
  --ablate-edge-type 0 \
  \
  >> ml/logs/ablation-et0-${LOG_SUFFIX}.log 2>&1 &

echo "Launched: ablation-et0-unknown"
sleep 5  # brief pause between launches

# --- ablate edge type 1 (AST_PARENT_OF) ---
# Estimated F1 impact: Neutral — syntax only, no semantic role in v8
TRANSFORMERS_OFFLINE=1 TRITON_CACHE_DIR=/tmp/triton_cache PYTHONPATH=. \
  nohup ml/.venv/bin/python ml/scripts/train.py \
  --gnn-layers 8 --gnn-prefix-k 48 --gnn-prefix-warmup-epochs 15 \
  --epochs 60 --batch-size 8 --gradient-accumulation-steps 8 \
  --loss-fn asl --compile --use-amp --phase2-edge-types 6 8 9 \
  --jk-entropy-reg-lambda 0.005 \
  --experiment-name sentinel-ablation-v1 \
  --run-name ablation-et1-ast_parent_of \
  --ablate-edge-type 1 \
  \
  >> ml/logs/ablation-et1-${LOG_SUFFIX}.log 2>&1 &

echo "Launched: ablation-et1-ast_parent_of"
sleep 5  # brief pause between launches

# --- ablate edge type 2 (CONTAINS) ---
# Estimated F1 impact: -0.03 to -0.06 F1 — loses CONTRACT→FUNCTION hierarchy
TRANSFORMERS_OFFLINE=1 TRITON_CACHE_DIR=/tmp/triton_cache PYTHONPATH=. \
  nohup ml/.venv/bin/python ml/scripts/train.py \
  --gnn-layers 8 --gnn-prefix-k 48 --gnn-prefix-warmup-epochs 15 \
  --epochs 60 --batch-size 8 --gradient-accumulation-steps 8 \
  --loss-fn asl --compile --use-amp --phase2-edge-types 6 8 9 \
  --jk-entropy-reg-lambda 0.005 \
  --experiment-name sentinel-ablation-v1 \
  --run-name ablation-et2-contains \
  --ablate-edge-type 2 \
  \
  >> ml/logs/ablation-et2-${LOG_SUFFIX}.log 2>&1 &

echo "Launched: ablation-et2-contains"
sleep 5  # brief pause between launches

# --- ablate edge type 3 (INHERITS) ---
# Estimated F1 impact: -0.01 to -0.03 F1 — minor; few inheritance edges in corpus
TRANSFORMERS_OFFLINE=1 TRITON_CACHE_DIR=/tmp/triton_cache PYTHONPATH=. \
  nohup ml/.venv/bin/python ml/scripts/train.py \
  --gnn-layers 8 --gnn-prefix-k 48 --gnn-prefix-warmup-epochs 15 \
  --epochs 60 --batch-size 8 --gradient-accumulation-steps 8 \
  --loss-fn asl --compile --use-amp --phase2-edge-types 6 8 9 \
  --jk-entropy-reg-lambda 0.005 \
  --experiment-name sentinel-ablation-v1 \
  --run-name ablation-et3-inherits \
  --ablate-edge-type 3 \
  \
  >> ml/logs/ablation-et3-${LOG_SUFFIX}.log 2>&1 &

echo "Launched: ablation-et3-inherits"
sleep 5  # brief pause between launches

# --- ablate edge type 4 (USES) ---
# Estimated F1 impact: Neutral — not used in any Phase 2/3 mask
TRANSFORMERS_OFFLINE=1 TRITON_CACHE_DIR=/tmp/triton_cache PYTHONPATH=. \
  nohup ml/.venv/bin/python ml/scripts/train.py \
  --gnn-layers 8 --gnn-prefix-k 48 --gnn-prefix-warmup-epochs 15 \
  --epochs 60 --batch-size 8 --gradient-accumulation-steps 8 \
  --loss-fn asl --compile --use-amp --phase2-edge-types 6 8 9 \
  --jk-entropy-reg-lambda 0.005 \
  --experiment-name sentinel-ablation-v1 \
  --run-name ablation-et4-uses \
  --ablate-edge-type 4 \
  \
  >> ml/logs/ablation-et4-${LOG_SUFFIX}.log 2>&1 &

echo "Launched: ablation-et4-uses"
sleep 5  # brief pause between launches

# --- ablate edge type 5 (REVERSE_CONTAINS) ---
# Estimated F1 impact: -0.04 to -0.08 F1 — loses CFG→FUNCTION upward signal (Phase 3 blind)
TRANSFORMERS_OFFLINE=1 TRITON_CACHE_DIR=/tmp/triton_cache PYTHONPATH=. \
  nohup ml/.venv/bin/python ml/scripts/train.py \
  --gnn-layers 8 --gnn-prefix-k 48 --gnn-prefix-warmup-epochs 15 \
  --epochs 60 --batch-size 8 --gradient-accumulation-steps 8 \
  --loss-fn asl --compile --use-amp --phase2-edge-types 6 8 9 \
  --jk-entropy-reg-lambda 0.005 \
  --experiment-name sentinel-ablation-v1 \
  --run-name ablation-et5-reverse_contains \
  --ablate-edge-type 5 \
  \
  >> ml/logs/ablation-et5-${LOG_SUFFIX}.log 2>&1 &

echo "Launched: ablation-et5-reverse_contains"
sleep 5  # brief pause between launches

# --- ablate edge type 6 (CONTROL_FLOW) ---
# Estimated F1 impact: -0.05 to -0.10 F1 — PRIMARY: CEI ordering signal lost
TRANSFORMERS_OFFLINE=1 TRITON_CACHE_DIR=/tmp/triton_cache PYTHONPATH=. \
  nohup ml/.venv/bin/python ml/scripts/train.py \
  --gnn-layers 8 --gnn-prefix-k 48 --gnn-prefix-warmup-epochs 15 \
  --epochs 60 --batch-size 8 --gradient-accumulation-steps 8 \
  --loss-fn asl --compile --use-amp --phase2-edge-types 6 8 9 \
  --jk-entropy-reg-lambda 0.005 \
  --experiment-name sentinel-ablation-v1 \
  --run-name ablation-et6-control_flow \
  --ablate-edge-type 6 \
  \
  >> ml/logs/ablation-et6-${LOG_SUFFIX}.log 2>&1 &

echo "Launched: ablation-et6-control_flow"
sleep 5  # brief pause between launches

# --- ablate edge type 7 (DEF_USE) ---
# Estimated F1 impact: -0.01 to -0.03 F1 — data flow signal for IntegerUO/UnusedReturn
TRANSFORMERS_OFFLINE=1 TRITON_CACHE_DIR=/tmp/triton_cache PYTHONPATH=. \
  nohup ml/.venv/bin/python ml/scripts/train.py \
  --gnn-layers 8 --gnn-prefix-k 48 --gnn-prefix-warmup-epochs 15 \
  --epochs 60 --batch-size 8 --gradient-accumulation-steps 8 \
  --loss-fn asl --compile --use-amp --phase2-edge-types 6 8 9 \
  --jk-entropy-reg-lambda 0.005 \
  --experiment-name sentinel-ablation-v1 \
  --run-name ablation-et7-def_use \
  --ablate-edge-type 7 \
  \
  >> ml/logs/ablation-et7-${LOG_SUFFIX}.log 2>&1 &

echo "Launched: ablation-et7-def_use"
sleep 5  # brief pause between launches

# --- ablate edge type 8 (CALL_ENTRY) ---
# Estimated F1 impact: -0.03 to -0.06 F1 — cross-function call signal
TRANSFORMERS_OFFLINE=1 TRITON_CACHE_DIR=/tmp/triton_cache PYTHONPATH=. \
  nohup ml/.venv/bin/python ml/scripts/train.py \
  --gnn-layers 8 --gnn-prefix-k 48 --gnn-prefix-warmup-epochs 15 \
  --epochs 60 --batch-size 8 --gradient-accumulation-steps 8 \
  --loss-fn asl --compile --use-amp --phase2-edge-types 6 8 9 \
  --jk-entropy-reg-lambda 0.005 \
  --experiment-name sentinel-ablation-v1 \
  --run-name ablation-et8-call_entry \
  --ablate-edge-type 8 \
  \
  >> ml/logs/ablation-et8-${LOG_SUFFIX}.log 2>&1 &

echo "Launched: ablation-et8-call_entry"
sleep 5  # brief pause between launches

# --- ablate edge type 9 (RETURN_TO) ---
# Estimated F1 impact: -0.02 to -0.05 F1 — return-site signal
TRANSFORMERS_OFFLINE=1 TRITON_CACHE_DIR=/tmp/triton_cache PYTHONPATH=. \
  nohup ml/.venv/bin/python ml/scripts/train.py \
  --gnn-layers 8 --gnn-prefix-k 48 --gnn-prefix-warmup-epochs 15 \
  --epochs 60 --batch-size 8 --gradient-accumulation-steps 8 \
  --loss-fn asl --compile --use-amp --phase2-edge-types 6 8 9 \
  --jk-entropy-reg-lambda 0.005 \
  --experiment-name sentinel-ablation-v1 \
  --run-name ablation-et9-return_to \
  --ablate-edge-type 9 \
  \
  >> ml/logs/ablation-et9-${LOG_SUFFIX}.log 2>&1 &

echo "Launched: ablation-et9-return_to"
sleep 5  # brief pause between launches

# --- ablate edge type 10 (DFG_GLOBAL) ---
# Estimated F1 impact: Neutral — not in Phase 2 mask for this run config
TRANSFORMERS_OFFLINE=1 TRITON_CACHE_DIR=/tmp/triton_cache PYTHONPATH=. \
  nohup ml/.venv/bin/python ml/scripts/train.py \
  --gnn-layers 8 --gnn-prefix-k 48 --gnn-prefix-warmup-epochs 15 \
  --epochs 60 --batch-size 8 --gradient-accumulation-steps 8 \
  --loss-fn asl --compile --use-amp --phase2-edge-types 6 8 9 \
  --jk-entropy-reg-lambda 0.005 \
  --experiment-name sentinel-ablation-v1 \
  --run-name ablation-et10-dfg_global \
  --ablate-edge-type 10 \
  \
  >> ml/logs/ablation-et10-${LOG_SUFFIX}.log 2>&1 &

echo "Launched: ablation-et10-dfg_global"
sleep 5  # brief pause between launches
